### PR TITLE
Completed html-skeleton exercise. - Barbara Liao

### PR DESCRIPTION
**Pull request by barbara-liao**
html-skeleton screenshot

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Barbara! This still seems to include the `exercises` directory, in addition to the `html-skeleton` directory. Please delete that `exercises` directory and its contents, then `add` and `commit` and `push` your work again.

**Comment by barbara-liao** [comment]
html-skeleton screenshot 2

**Comment by barbara-liao** [comment]
Good catch! I forgot to update the screenshot after the push.

**Review by codingcodymiller — APPROVED** [review]
Woohoo!!! Success!!! 🙌

**Pull request merged**
